spring.application.name=microcommerce

# ====================== H2 Database ======================
spring.datasource.url=jdbc:h2:mem:microsserviceDB
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Désactiver la génération automatique de Hibernate
# (on va tout gérer nous-mêmes dans schema.sql)
spring.jpa.hibernate.ddl-auto=none

# Afficher les requêtes SQL (utile pour debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Initialisation des scripts SQL
spring.sql.init.mode=always
spring.sql.init.continue-on-error=false
# Important pour Spring Boot 4 + JPA : exécuter les scripts APRÈS Hibernate
spring.jpa.defer-datasource-initialization=true